services:
  odoo:
    build: .
    container_name: odoo16
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./:/mnt/extra-addons/ww_sale_whatsapp-16
      - odoo-web-data:/var/lib/odoo
    # REMOVEMOS a linha "command" para permitir a configuração manual
    environment:
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    restart: always

  db:
    image: postgres:14
    container_name: postgres14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  waha:
    image: devlikeapro/waha
    container_name: waha
    ports:
      - "4000:3000"
    volumes:
      - waha-sessions:/app/.sessions
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data:
  waha-sessions: