{
    "name": "Enviar por WhatsApp",
    "version": "16.0.2.0.0",
    "summary": "Botão no Pedido de Venda e Compra para enviar PDF",
    "author": "Work Wise Consulting",
    "license": "LGPL-3",
    "depends": [
        "base",
        "base_setup",
        "sale_management",
        "purchase",
        "mail",
        "sale",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/sale_order_views.xml",
        "views/purchase_order_views.xml",
        "views/whatsapp_wizard_views.xml",
        "views/res_config_settings_view.xml",
        "views/service_definition_views.xml",
    ],
    "installable": True,
    "application": False,
}